services:
  mysql:
    container_name: 'mysql-desafiomagalu'
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=desafiomagalu'
      - 'MYSQL_PASSWORD=Chelo1337,'
      - 'MYSQL_ROOT_PASSWORD=Chelo1337,'
      - 'MYSQL_USER=admin'
    ports:
      - '3306:3306'